# Generated by Django 4.2.2 on 2023-06-11 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('rating', models.CharField(blank=True, choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg13'), ('R', 'R'), ('NC-17', 'Nc17')], default='G', max_length=20, null=True)),
                ('synopsis', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
